version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/a11y-library
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/alert
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/alert-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/animation-library
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/ariakit-library
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/aspect-ratio
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/badge
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/box-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/button
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/button-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/checkbox
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/core
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/descendants-library
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/dialog
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/dialog-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/elements-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/field
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/flex
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/icon
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/input
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/link
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/menu
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/menu-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/pin-input
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/popover
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/popover-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/portal-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/radio-group
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/select
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/select-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/separator
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/separator-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/spinner
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/stack
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/state-library
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/styled-library
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/textarea
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/toaster
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/tooltip
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/tooltip-primitive
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/truncate
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/typography
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/utils-library
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/visually-hidden
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
