version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/box
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/button
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/core
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/icon
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/input
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/spinner
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/styling
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/primitives/text
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/theme
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/typography
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/utils
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/components/visually-hidden
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
