version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/box
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/button
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/core
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/icon
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/libraries/styling
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/theme
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/typography
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
  - package-ecosystem: npm
    directory: /packages/utils
    schedule:
      interval: weekly
    labels:
      - 'area: infra'
      - 'area: security'
      - 'area: repo'
