# https://github.com/actions/labeler

# Add 'repo' label to any root file changes
'area: repo':
- changed-files:
  - any-glob-to-any-file: '*'

'area: infra':
- changed-files:
  - any-glob-to-any-file:
    - .changeset/**/*
    - .github/**/*
    - .husky/**/*
    - _storybook/**/*
    - .vscode/**/*
    - tools/**/*
    - package.json

# components
'area: components':
- changed-files:
  - any-glob-to-any-file: packages/components/**/*

# core bundle
'area: core':
  - changed-files:
  - any-glob-to-any-file: packages/core/**/*

# libraries
'area: libraries':
- changed-files:
  - any-glob-to-any-file: packages/libraries/**/*

# primitives
'area: primitives':
- changed-files:
  - any-glob-to-any-file: packages/primitives/**/*

# docs
'type: storybook':
- changed-files:
  - any-glob-to-any-file:
    - packages/**/stories/**/*
    - _storybook/**/*

# tests
'type: test':
- changed-files:
  - any-glob-to-any-file: '**/__tests__/**/*'
