# https://github.com/actions/labeler

# Add 'repo' label to any root file changes
'area: repo':
  - '*'

'area: infra':
  - .changeset/**/*
  - .github/**/*
  - .husky/**/*
  - .storybook/**/*
  - .vscode/**/*
  - tools/**/*
  - package.json

# components
'area: components':
  - packages/components/**/*

# core bundle
'area: core':
  - packages/core/**/*

# libraries
'area: libraries':
  - packages/libraries/**/*

# primitives
'area: primitives':
  - packages/primitives/**/*

# docs
'type: storybook':
  - packages/**/stories/**/*
  - .storybook/**/*

# tests
'type: test':
  - '**/__tests__/**/*'
