# https://github.com/actions/labeler

# Add 'repo' label to any root file changes
'area: repo':
  - '*'

'area: infra':
  - .changeset/**/*
  - .github/**/*
  - .husky/**/*
  - .storybook/**/*
  - .vscode/**/*
  - tools/**/*

'area: core':
  - packages/core/**/*

'area: box':
  - packages/box/**/*

'area: button':
  - packages/button/**/*

'area: icon':
  - packages/icon/core-bundle/**/*

'area: libraries':
  - packages/libraries/**/*

'area: styling':
  - packages/libraries/styling/**/*

'area: theme':
  - packages/theme/**/*

'area: typography':
  - packages/typography/**/*

'area: utils':
  - packages/utils/**/*

'type: storybook':
  - packages/**/stories/**/*

'type: test':
  - '**/__tests__/**/*'
