# https://github.com/actions/labeler

# Add 'repo' label to any root file changes
'area: repo':
  - '*'

'area: infra':
  - .changeset/**/*
  - .github/**/*
  - .husky/**/*
  - .storybook/**/*
  - .vscode/**/*
  - tools/**/*

# components
'area: components':
  - packages/components/**/*
'area: button':
  - packages/components/button/**/*
'area: icon':
  - packages/components/icon/core-bundle/**/*
'area: theme':
  - packages/components/theme/**/*
'area: typography':
  - packages/components/typography/**/*

# core bundle
'area: core':
  - packages/core/**/*

# libraries
'area: libraries':
  - packages/libraries/**/*
'area: styling':
  - packages/libraries/styling/**/*
'area: utils':
  - packages/utils/**/*

# primitives
'area: primitives':
  - packages/primitives/**/*
'area: box':
  - packages/primitives/box/**/*

# docs
'type: storybook':
  - packages/**/stories/**/*

# tests
'type: test':
  - '**/__tests__/**/*'
