name: Setup Env and Dependencies
description: Checkout repo, setup env and install dependencies
outputs:
  cache-hit:
    description: Yarn cache hit flag
    value: ${{ steps.yarn_cache_id.outputs.cache-hit || steps.node_modules_cache_id.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup nodejs
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Get yarn cache directory path
      shell: bash
      id: yarn_cache_dir_path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - name: Load yarn cache
      uses: actions/cache@v2
      id: yarn_cache_id
      with:
        path: ${{ steps.yarn_cache_dir_path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn

    - name: Load node modules cache
      uses: actions/cache@v2
      id: node_modules_cache_id
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
