name: Merge to main

on:
  push:
    paths:
      - "packages/**"
      - ".changeset/*"
    branches:
      - main

jobs:
  version-packages:
    name: Version packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup workflow
        id: workflow_setup_step
        uses: '@bigwoof91/real-system/.github/actions/workflow_setup@testing-github-actions'

      - name: Version packages and create pull request
        uses: changesets/action@master
        with:
          version: yarn version:stable
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
