name: Merge to main

on:
  push:
    branches:
      - main

jobs:
  version-or-publish-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        id: env_setup
        uses: bigwoof91/real-system/.github/actions/setup-env@main

      - name: Yarn install
        if: steps.env_setup.outputs.cache-hit != 'true'
        run: yarn install --immutable
        
      - name: Create PR or Publish Package
        uses: changesets/action@master
        with:
          version: yarn version:stable
          publish: yarn release:stable
          commit: "chore(release): publish packages"
          title: "chore(release): publish packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
