name: Merge to main

on:
  push:
    paths:
      - "packages/**"
      - ".changeset/*"
    branches:
      - main

jobs:
  version-packages:
    name: Version packages
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        id: env_setup
        uses: bigwoof91/real-system/.github/actions/setup-env@main

      - name: Yarn install
        if: steps.env_setup.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Version packages and create pull request
        uses: changesets/action@master
        with:
          version: yarn version:stable
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
