name: Tests

on:
  pull_request:
    paths:
      - 'packages/**'
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        id: env_setup
        uses: bigwoof91/real-system/.github/actions/setup-env@main

      - name: Yarn install
        if: steps.env_setup.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Run lint
        run: yarn lint
      
      - name: Run typechecks
        run: yarn typecheck

      - name: Run tests
        run: yarn test
  package-size:
    name: Diff compressed package sizes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 16.16.0
        uses: actions/setup-node@master
        with:
          node-version: 16.16.0

      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          build-script: 'build:js'
          # only check commonjs files
          pattern: '**/lib/**/*.js'
          exclude: '{**/*.map,**/node_modules/**,**/*.debug.js,**/*.esm.js}'
