name: Unit Tests

on:
  push:
    paths:
      - "packages/**"
    branches:
      - main 
  pull_request:
    paths:
        - "packages/**"
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        id: env_setup
        uses: bigwoof91/real-system/.github/actions/setup-env@testing-github-actions

      - name: Yarn install
        if: steps.env_setup.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Run tests
        run: yarn test
