name: Unit Tests

on:
  push:
    paths:
      - "packages/**"
    branches:
      - main 
  pull_request:
    paths:
        - "packages/**"
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup and install deps
        id: workflow_setup_step
        uses: action/workflow_setup@v1

      - name: Run tests
        run: yarn test
