name: Unit Tests

on:
  push:
    paths:
      - "packages/**"
    branches:
      - main 
  pull_request:
    paths:
        - "packages/**"
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup and install deps
        id: workflow_setup_step
        uses: bigwoof91/real-system/.github/actions/workflow_setup@testing-github-actions

      - name: Run tests
        run: yarn test
